# Generated by Django 3.1.7 on 2021-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_DOPOKS',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_OKS',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_OKVED',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_achievements',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_dolshnost',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='memberinfo_job_telephone',
        ),
    ]
