# Generated by Django 3.1.6 on 2021-03-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова эксперта')),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.member', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Ключевые слова эксперта',
            },
        ),
        migrations.CreateModel(
            name='ExpertArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.FileField(blank=True, upload_to='', verbose_name='Docx файл со статьей')),
                ('article_keywords', models.TextField(blank=True, verbose_name='Ключевые слова статьи')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Статьи эксперта',
            },
        ),
    ]
