# Generated by Django 3.1.7 on 2021-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='memberinfo_dateofbirth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='memberinfo_education',
            field=models.CharField(choices=[('higher', 'Высшее'), ('middle', 'Среднее'), ('middle_special', 'Среднее-специальное'), ('after_univ', 'Послевузовское')], max_length=500, verbose_name='Образование'),
        ),
    ]
