# Generated by Django 3.1.7 on 2021-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertarticle',
            name='article_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова статьи'),
        ),
    ]
