# Generated by Django 3.1.6 on 2021-03-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencesections',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='conferencesections',
            name='conference_sections_conference_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.conference', verbose_name='Секция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferencesections',
            name='conference_sections_name',
            field=models.CharField(max_length=50, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='member_application_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='member_application_status',
            field=models.CharField(choices=[('Consideration', 'На рассмотрении'), ('Denial', 'Отказ'), ('Approved', 'Одобрено'), ('Revision', 'На доработку')], default='Consideration', max_length=100, verbose_name='Статус рассмотрения'),
        ),
    ]
