# Generated by Django 3.1.6 on 2021-03-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210301_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesections',
            name='conference_sections_conference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conference', verbose_name='Конференция'),
        ),
    ]
