# Generated by Django 3.1.7 on 2021-05-15 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210515_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='memberinfo_dateofbirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
