# Generated by Django 3.2.1 on 2021-05-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210515_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_keywords',
            field=models.TextField(blank=True, verbose_name='Ключевые слова конференции'),
        ),
    ]
