# Generated by Django 3.1.6 on 2021-03-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210301_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Пользователь_прокси', 'verbose_name_plural': 'Пользователи_прокси'},
        ),
        migrations.RenameField(
            model_name='memberapplication',
            old_name='member_application_status',
            new_name='app_status',
        ),
        migrations.RenameField(
            model_name='memberapplication',
            old_name='member_conference_id',
            new_name='conference_id',
        ),
        migrations.RenameField(
            model_name='memberapplication',
            old_name='member_application_comment',
            new_name='expert_app_comment',
        ),
        migrations.RenameField(
            model_name='memberapplication',
            old_name='member_file',
            new_name='speech_file',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='member_name',
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='co_authors',
            field=models.TextField(default=123123123, max_length=500, verbose_name='Соавторы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expert', to='core.member', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='hotel_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Гостиница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='invitation_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Приглашение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='member', to='core.member', verbose_name='Участник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='member_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.conferencesections', verbose_name='Секция'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='participation_form',
            field=models.CharField(choices=[('Ochnoe', 'Очное'), ('Zaochnoe', 'Заочное'), ('OchZaoch', 'Очно-заочное')], default='Ochnoe', max_length=100, verbose_name='Формат участия в конференции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='speech_annotation',
            field=models.TextField(default='asdasdasdasd', max_length=1000, verbose_name='Аннотация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='speech_keywords',
            field=models.CharField(default='asdasdads', max_length=100, verbose_name='Ключевые слова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='speech_name',
            field=models.CharField(default='adasdasda', max_length=100, verbose_name='Название темы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_format_id',
            field=models.CharField(choices=[('Ochnoe', 'Очное'), ('Zaochnoe', 'Заочное'), ('OchZaoch', 'Очно-заочное')], max_length=500, verbose_name='Формат проведения конференции'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='memberinfo_user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='Пользователь'),
        ),
    ]
