# Generated by Django 3.1.7 on 2021-04-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210420_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberapplication',
            unique_together=set(),
        ),
    ]
